name: .NET Build

# Trigger the workflow on push or pull request
on:
  push:
    branches: ["master"]
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.axaml"
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - ".github/workflows/dotnet.yaml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Download repo and submodules
      run: | 
        git submodule update --init --recursive
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and pack release
      run: dotnet pack -c Release

    - name: Add .nupkg as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Nuget .nupkg
        path: ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.Utils.1.0.0.nupkg

    - name: Upload to nuget repo
      run: |
        git config --global user.name "Github Actions Bot"
        git config --global user.email "<>"
        git config --global credential.helper cache
        git clone https://${{secrets.ACCESS_TOKEN}}@github.com/OpenSteamClient/nuget
        cp ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.Utils.1.0.0.nupkg nuget/flatcontainer/opensteamworks.utils/1.0.0/opensteamworks.utils.1.0.0.nupkg -f
        cd nuget
        git add flatcontainer/opensteamworks.utils/1.0.0/opensteamworks.utils.1.0.0.nupkg
        git commit -m "$(date)"
        git push

    
